Updates for unified-cfg-file configuration

diff --git a/inbound_email/bin/cs_mailin-local-poller b/inbound_email/bin/cs_mailin-local-poller
--- a/inbound_email/bin/cs_mailin-local-poller
+++ b/inbound_email/bin/cs_mailin-local-poller
@@ -1,19 +1,10 @@
 #!/bin/bash
 
-#desc# Collect mail from the development inbound mail server and save it to the local queue
+#desc# Collect mail from the development inbound mail server and save it to the local poller-stage directory
 
-# localMailRoot=$CS_MAILIN_MAILQ_TOP
-# localInboundMailDir=$CS_MAILIN_DIRECTORY
-localInboundMailDir=`eval echo $(get-json-property -j $CS_MAILIN_CFG_FILE -p inboundEmailServer.inboundEmailDirectory)`
-localMailRoot=$(cd $localInboundMailDir/.. && pwd)
-# mailserver=$CS_MAILIN_INBOUND_MAIL_SERVER
-# maildir=$CS_MAILIN_INBOUND_MAIL_DIR
+
+localMailRoot=$(cd $CS_MAILIN_INBOUND_EMAIL_DIRECTORY/.. && pwd)
 localMailStagingDir="$localMailRoot/poller-stage"
-echo "
-localMailRoot:       $localMailRoot
-localInboundMailDir: $localInboundMailDir
-localMailStagingDir: $localMailStagingDir
-"
 
 function usage {
 	echo "usage: $0 -p polling_interval"
@@ -31,10 +22,10 @@ shift `expr $OPTIND - 1`
 [ -z "$poll_interval" ] && usage
 
 
-ssh $CS_MAILIN_INBOUND_MAIL_SERVER echo hi >/dev/null
-[ $? -ne 0 ] && echo "Test ssh to $CS_MAILIN_INBOUND_MAIL_SERVER unsuccessful" && exit 1
+ssh $CS_MAILIN_REMOTE_INBOUND_MAIL_SERVER echo hi >/dev/null
+[ $? -ne 0 ] && echo "Test ssh to $CS_MAILIN_REMOTE_INBOUND_MAIL_SERVER unsuccessful" && exit 1
 
-[ ! -d $localInboundMailDir ] && echo "creating $localInboundMailDir" && mkdir -p $localInboundMailDir
+[ ! -d $CS_MAILIN_INBOUND_EMAIL_DIRECTORY ] && echo "creating $CS_MAILIN_INBOUND_EMAIL_DIRECTORY" && mkdir -p $CS_MAILIN_INBOUND_EMAIL_DIRECTORY
 [ ! -d $localMailStagingDir ] && echo "creating $localMailStagingDir" && mkdir -p $localMailStagingDir
 
 while [ 1 ]
@@ -45,14 +36,14 @@ do
 		exit
 	fi
 
-	numFilesToCopy=`ssh $CS_MAILIN_INBOUND_MAIL_SERVER "ls $CS_MAILIN_INBOUND_MAIL_DIR|wc -l"`
+	numFilesToCopy=`ssh $CS_MAILIN_REMOTE_INBOUND_MAIL_SERVER "ls $CS_MAILIN_REMOTE_INBOUND_MAIL_DIR|wc -l"`
 	if [ $numFilesToCopy -gt 0 ]; then
-		scp $CS_MAILIN_INBOUND_MAIL_SERVER:$CS_MAILIN_INBOUND_MAIL_DIR/* $localMailStagingDir
-		[ $? -ne 0 ] && echo "scp $CS_MAILIN_INBOUND_MAIL_SERVER:$CS_MAILIN_INBOUND_MAIL_DIR/* $localMailStagingDir FAILED" && exit 1
-		/bin/mv $localMailStagingDir/* $localInboundMailDir
-		[ $? -ne 0 ] && echo "/bin/mv $localMailStagingDir/* $localInboundMailDir FAILED" && exit 1
-		ssh $CS_MAILIN_INBOUND_MAIL_SERVER "/bin/rm -f $CS_MAILIN_INBOUND_MAIL_DIR/*"
-		[ $? -ne 0 ] && echo "ssh $CS_MAILIN_INBOUND_MAIL_SERVER \"/bin/echo -f $CS_MAILIN_INBOUND_MAIL_DIR/*\" FAILED"
+		scp $CS_MAILIN_REMOTE_INBOUND_MAIL_SERVER:$CS_MAILIN_REMOTE_INBOUND_MAIL_DIR/* $localMailStagingDir
+		[ $? -ne 0 ] && echo "scp $CS_MAILIN_REMOTE_INBOUND_MAIL_SERVER:$CS_MAILIN_REMOTE_INBOUND_MAIL_DIR/* $localMailStagingDir FAILED" && exit 1
+		/bin/mv $localMailStagingDir/* $CS_MAILIN_INBOUND_EMAIL_DIRECTORY
+		[ $? -ne 0 ] && echo "/bin/mv $localMailStagingDir/* $CS_MAILIN_INBOUND_EMAIL_DIRECTORY FAILED" && exit 1
+		ssh $CS_MAILIN_REMOTE_INBOUND_MAIL_SERVER "/bin/rm -f $CS_MAILIN_REMOTE_INBOUND_MAIL_DIR/*"
+		[ $? -ne 0 ] && echo "ssh $CS_MAILIN_REMOTE_INBOUND_MAIL_SERVER \"/bin/echo -f $CS_MAILIN_REMOTE_INBOUND_MAIL_DIR/*\" FAILED"
 		echo "$numFilesToCopy files processed"
 	else
 		echo "no files found"
