Inbound email server now supports a configuration file

diff --git a/inbound_email/bin/cs_mailin-local-poller b/inbound_email/bin/cs_mailin-local-poller
--- a/inbound_email/bin/cs_mailin-local-poller
+++ b/inbound_email/bin/cs_mailin-local-poller
@@ -2,11 +2,18 @@
 
 #desc# Collect mail from the development inbound mail server and save it to the local queue
 
-localtop=$CS_MAILIN_MAILQ_TOP
-localin=$CS_MAILIN_DIRECTORY
-mailserver=$CS_MAILIN_INBOUND_MAIL_SERVER
-maildir=$CS_MAILIN_INBOUND_MAIL_DIR
-localstage="$localtop/poller-stage"
+# localMailRoot=$CS_MAILIN_MAILQ_TOP
+# localInboundMailDir=$CS_MAILIN_DIRECTORY
+localInboundMailDir=`eval echo $(get-json-property -j $CS_MAILIN_CFG_FILE -p inboundEmailServer.inboundEmailDirectory)`
+localMailRoot=$(cd $localInboundMailDir/.. && pwd)
+# mailserver=$CS_MAILIN_INBOUND_MAIL_SERVER
+# maildir=$CS_MAILIN_INBOUND_MAIL_DIR
+localMailStagingDir="$localMailRoot/poller-stage"
+echo "
+localMailRoot:       $localMailRoot
+localInboundMailDir: $localInboundMailDir
+localMailStagingDir: $localMailStagingDir
+"
 
 function usage {
 	echo "usage: $0 -p polling_interval"
@@ -24,28 +31,28 @@ shift `expr $OPTIND - 1`
 [ -z "$poll_interval" ] && usage
 
 
-ssh $mailserver echo hi >/dev/null
-[ $? -ne 0 ] && echo "Test ssh to $mailserver unsuccessful" && exit 1
+ssh $CS_MAILIN_INBOUND_MAIL_SERVER echo hi >/dev/null
+[ $? -ne 0 ] && echo "Test ssh to $CS_MAILIN_INBOUND_MAIL_SERVER unsuccessful" && exit 1
 
-[ ! -d $localin ] && echo "creating $localin" && mkdir -p $localin
-[ ! -d $localstage ] && echo "creating $localstage" && mkdir -p $localstage
+[ ! -d $localInboundMailDir ] && echo "creating $localInboundMailDir" && mkdir -p $localInboundMailDir
+[ ! -d $localMailStagingDir ] && echo "creating $localMailStagingDir" && mkdir -p $localMailStagingDir
 
 while [ 1 ]
 do
-	if [ -f $localtop/stop ]; then
+	if [ -f $localMailRoot/stop ]; then
 		echo "Stop request detected"
-		/bin/rm $localtop/stop
+		/bin/rm $localMailRoot/stop
 		exit
 	fi
 
-	numFilesToCopy=`ssh $mailserver "ls $maildir|wc -l"`
+	numFilesToCopy=`ssh $CS_MAILIN_INBOUND_MAIL_SERVER "ls $CS_MAILIN_INBOUND_MAIL_DIR|wc -l"`
 	if [ $numFilesToCopy -gt 0 ]; then
-		scp $mailserver:$maildir/* $localstage
-		[ $? -ne 0 ] && echo "scp $mailserver:$maildir/* $localstage FAILED" && exit 1
-		/bin/mv $localstage/* $localin
-		[ $? -ne 0 ] && echo "/bin/mv $localstage/* $localin FAILED" && exit 1
-		ssh $mailserver "/bin/rm -f $maildir/*"
-		[ $? -ne 0 ] && echo "ssh $mailserver \"/bin/echo -f $maildir/*\" FAILED"
+		scp $CS_MAILIN_INBOUND_MAIL_SERVER:$CS_MAILIN_INBOUND_MAIL_DIR/* $localMailStagingDir
+		[ $? -ne 0 ] && echo "scp $CS_MAILIN_INBOUND_MAIL_SERVER:$CS_MAILIN_INBOUND_MAIL_DIR/* $localMailStagingDir FAILED" && exit 1
+		/bin/mv $localMailStagingDir/* $localInboundMailDir
+		[ $? -ne 0 ] && echo "/bin/mv $localMailStagingDir/* $localInboundMailDir FAILED" && exit 1
+		ssh $CS_MAILIN_INBOUND_MAIL_SERVER "/bin/rm -f $CS_MAILIN_INBOUND_MAIL_DIR/*"
+		[ $? -ne 0 ] && echo "ssh $CS_MAILIN_INBOUND_MAIL_SERVER \"/bin/echo -f $CS_MAILIN_INBOUND_MAIL_DIR/*\" FAILED"
 		echo "$numFilesToCopy files processed"
 	else
 		echo "no files found"
