Added server_utils as a git submodule, playground template and npm install in src

diff --git a/outbound_email/sandbox/configure-sandbox b/outbound_email/sandbox/configure-sandbox
--- a/outbound_email/sandbox/configure-sandbox
+++ b/outbound_email/sandbox/configure-sandbox
@@ -21,19 +21,21 @@ abort_on_fail=1
 # Place any commands needed to prepare the sandbox for use here. Assume the
 # environment is set
 
-cd $CS_OUTBOUND_EMAIL_TOP
+cd $CS_OUTBOUND_EMAIL_TOP || exit 1
 
 # Install git submodules
 [ -f .gitmodules ] && git submodule update --init --recursive
+
+cd src || exit 1
 
 # Exmaple: expanding templates
 # $DT_TOP/bin/create-file-from-template.py -t $XYZ_SANDBOX/git_project/etc/httpd.conf.template -o $XYZ_SANDBOX/conf/httpd.conf
 
 # If the sandbox uses node, wipe the node_modules and re-install during re-configuration
-if [ -f $CS_OUTBOUND_EMAIL_TOP/package.json -a -n "$CS_OUTBOUND_EMAIL_NODE_VER" ]; then
-	[ -d $CS_OUTBOUND_EMAIL_TOP/node_modules ] && /bin/rm -rf $CS_OUTBOUND_EMAIL_TOP/node_modules
+if [ -f package.json -a -n "$CS_OUTBOUND_EMAIL_NODE_VER" ]; then
+	[ -d node_modules ] && /bin/rm -rf node_modules
 	if [ "$CS_OUTBOUND_EMAIL_YARN" == true ]; then
-		[ ! -f $CS_OUTBOUND_EMAIL_TOP/yarn.lock ] && echo "WARNING: yarn.lock not found - creating one"
+		[ ! -f yarn.lock ] && echo "WARNING: yarn.lock not found - creating one"
 		echo "yarn install (from `pwd`)"
 		yarn install --frozen-lockfile
 		[ $? -ne 0 ] && echo "yarn install failed" && [ $abort_on_fail -eq 1 ] && exit 1
